package pl.skolimowski.musicapp

object MusicRepoMock {
    fun getStreamUrls(): List<String> {
        return listOf<String>(
            "https://api.audius.co/v1/tracks/Kz2Qb9O/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/OG58jxv/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/x2V9AN7/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/WVlaNRB/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/Kpo9lmB/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/Y9kaAEy/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/329z4MJ/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/B0mpqjJ/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/7mjpzj/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/gWddGy9/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/lZQzr8O/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/rpEgqg/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/WkZNay9/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/JbqjARY/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/AQjlZ90/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/Og8pPyQ/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/oRW0WzR/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/0d1b1yV/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/mQAj1zp/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/gJWB3mZ/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/54jgPN2/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/p52JKAM/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/6kaProb/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/jbmXwE4/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/dy7aMqm/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/oWrqPKv/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/P970OqJ/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/g6WN319/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/xkO4qyX/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/ZEV95Rq/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/lv2GaqA/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/Al0OAaw/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/K9alvAB/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/aPq25Kz/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/YodwXKm/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/l5bo90l/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/yGwl374/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/OxbEloV/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/2VYrQ1/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/aZ9jW8E/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/NYWN8NY/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/ljrRrqG/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/NRMAKjQ/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/J5kbXBz/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/P9wdKa7/stream?app_name=MusicAiExampleApp",
            "https://api.audius.co/v1/tracks/yy8N5YY/stream?app_name=MusicAiExampleApp",
        )
    }
}